version: '3.5'

services:
  db_auth:
    container_name: postgres-airflow-scrapy
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1
    image: postgres:15.3-alpine